server:
    port: 7777
    host: 127.0.0.1
telegram:
    use_yn: Y
    token: 5626123:AAH1ZQGHP0QRIAjh50wTEUjMx6L-sZo-gBk
    chat_ids:
        - "5616601555"
info:
    email: test@test.com
    name: 홍길동
    nickname: 길동
    birth_date: 800622
    phone: 010-1234-5678
    car_number: 123구1234
    member_adult: 2
    member_teen: 0
    member_child: 1
