server:
    port: 7777
    host: "127.0.0.1"

telegram:
    use_yn: "Y"
    token: "56Bk"
    chat_ids: # 여러 명의 ID를 리스트로 관리
        - "56166"

info:
    email: "hm.com"
    birthday: "8002"
    name: "ㅈㅈㅈ"
    nickname: "ㄹㄹㄹ"
    phone: "010-1234-5678"
    car_number: "ㄹㄹㄹ"
    member_teen: 0
    member_adult: 2
    member_child: 0
